time_to_answer/config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get  'welcome/index'
    get  'search', to: 'search#questions'
    get  'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    get 'zip_code', to: 'zip_code#show'
  end
  namespace :admins_backoffice do
    get 'welcome/index' # Dashboard
    resources :admins   # Administradores
    resources :subjects # Assuntos/Áreas
    resources :questions # Perguntas
  end
  
  devise_for :admins, skip:  [:registrations]
  devise_for :users
 
  get 'inicio', to: 'site/welcome#index'
  get 'backoffice', to: 'admins_backoffice/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

time_to_answer/app/controllers/users_backoffice/profile_controller.rb
class UsersBackoffice::ProfileController < UsersBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_user
  
  def edit
    @user.build_user_profile if @user.user_profile.blank?
  end

  def update
    if @user.update(params_user)
      bypass_sign_in(@user)
      unless params_user[:user_profile_attributes][:avatar]
        redirect_to users_backoffice_profile_path, notice: "Usuário atualizado com sucesso!"
      end
    else
      render :edit
    end    
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def params_user
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation,
    user_profile_attributes: [:id, :address, :zip_code, :gender, :birthdate, :avatar])
  end

  def verify_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].extract!(:password, :password_confirmation)
    end
  end
end

time_to_answer/app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
    @user_statistic = UserStatistic.find_or_create_by(user: current_user)
  end
end

time_to_answer/app/controllers/users_backoffice/zip_code_controller.rb
class UsersBackoffice::ZipCodeController < UsersBackofficeController
  def show
    @cep = CEP.new(params[:zip_code])
  end
end

time_to_answer/app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  before_action :build_profile
  layout 'users_backoffice'

  private

  def build_profile
    current_user.build_user_profile if current_user.user_profile.blank?
  end
end

time_to_answer/app/helpers/users_backoffice/profile_helper.rb
module UsersBackoffice::ProfileHelper
  def gender_select(user, current_gender)
    user.user_profile.gender == current_gender ? 'btn-primary' : 'btn-default'
  end
end

time_to_answer/app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

time_to_answer/app/helpers/users_backoffice/zip_code_helper.rb
module UsersBackoffice::ZipCodeHelper
end

time_to_answer/app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
  def avatar_url
     avatar = current_user.user_profile.avatar
     avatar.attached? ? avatar : 'img.jpg'
  end
  

end

time_to_answer/app/views/users_backoffice/profile/edit.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Dados do Perfil</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <% if @user.errors.any? %>
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                
                <ul>
                  <% @user.errors.full_messages.each do |message| %>
                    <li> <%= message %> </li>
                  <% end %>
                </ul>
            </div>
        <% end %>
        <%= form_with(url: users_backoffice_profile_path, model: @user , local: true, class:"form-horizontal form-label-left") do |form| %>

          <div class="form-group">
              <%= form.label :first_name, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= form.text_field :first_name, class:"form-control col-md-7 col-xs-12" %>
              </div>
          </div>
          <div class="form-group">
              <%= form.label :last_name, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= form.text_field :last_name, class:"form-control col-md-7 col-xs-12" %>
              </div>
          </div>
          <div class="form-group">
              <%= form.label :email, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= form.text_field :email, 
                        class:"form-control col-md-7 col-xs-12", 
                        readonly: true  %>
              </div>
          </div>

          <%= form.fields_for :user_profile do |profile_form|  %>
            <div class="form-group">
                <%= profile_form.label :zip_code, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <div class="input-group">
                    <%= profile_form.text_field :zip_code, class:"form-control col-md-7 col-xs-12"%>
                    <span class="input-group-btn">
                        <%= link_to "Buscar", users_backoffice_zip_code_path, remote:true, class:"btn btn-primary", id:"zip-code-link" %>
                    </span>
                  </div>
                </div>
            </div>

            <script>
              let zip_code_input = document.getElementById("user_user_profile_attributes_zip_code");
              var zip_code_link = document.getElementById("zip-code-link");

              zip_code_input.addEventListener("change", function(){
                zip_code_link.href = '<%= users_backoffice_zip_code_path %>/?zip_code='+zip_code_input.value;
              });
            </script>


            <div class="form-group">
                <%= profile_form.label :address, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= profile_form.text_field :address, class:"form-control col-md-7 col-xs-12"%>
                </div>
            </div>

            <div class="form-group">
              <%= profile_form.label :gender, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <div id="gender" class="btn-group" data-toggle="buttons">
                  <label class="btn <%= gender_select(@user, 'M') %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                    <%= profile_form.radio_button :gender, "M", "data-parsley-multiple":"gender"%> &nbsp; Masculino &nbsp;
                  </label>
                  <label class="btn <%= gender_select(@user, 'F') %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                    <%= profile_form.radio_button :gender, "F", "data-parsley-multiple":"gender"%> &nbsp; Feminino &nbsp;
                  </label>
                </div>
              </div>
            </div>

            <%= javascript_tag do %>
               var labels = document.querySelectorAll('div#gender label');

               labels.forEach((label) => {
                 label.addEventListener('click', () => {
                   label.classList.remove('btn-default');
                   label.classList.add('btn-primary');

                   labels.forEach((lbl) => {
                     if(lbl !== label){
                        lbl.classList.remove('btn-primary');
                        lbl.classList.add('btn-default');
                     };
                   });
                 });
               });
            <% end %>

            <div class="form-group">
                <%= profile_form.label :birthdate, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= profile_form.text_field :birthdate, 
                      value: (l(@user.user_profile.birthdate) unless @user.user_profile.birthdate.blank?) ,
                      class:"form-control col-md-7 col-xs-12 datepicker"%>
                </div>
            </div>
          <% end %>
          
          <div class="form-group">
              <%= form.label :password, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= form.password_field :password, 
                        class:"form-control col-md-7 col-xs-12" %>
              </div>
          </div>

          <div class="form-group">
              <%= form.label :password_confirmation, class:"control-label col-md-3 col-sm-3 col-xs-12" %>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= form.password_field :password_confirmation, 
                        class:"form-control col-md-7 col-xs-12" %>
              </div>
          </div>

          <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
              <button type="submit" class="btn btn-success">Enviar</button>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

time_to_answer/app/views/users_backoffice/profile/update.js.erb
$('#avatarModal').modal('hide');

document.getElementById('imgAvatarLg').src = "<%= url_for(@user.user_profile.avatar) %>"
document.getElementById('imgAvatarMd').src = "<%= url_for(@user.user_profile.avatar) %>"
document.getElementById('imgAvatarSm').src = "<%= url_for(@user.user_profile.avatar) %>"

$.bootstrapGrowl('Avatar atualizado com sucesso!', {
  type: 'success', // (null, 'info', 'danger', 'success')
  align: 'right', // ('left', 'right', or 'center')
  allow_dismiss: true, // If true then will display a cross to close the popup.
  stackup_spacing: 10 // spacing between consecutively stacked growls.
});