time_to_answer/config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get  'welcome/index'
    get  'search', to: 'search#questions'
    get  'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    get 'zip_code', to: 'zip_code#show'
  end
  namespace :admins_backoffice do
    get 'welcome/index' # Dashboard
    resources :admins   # Administradores
    resources :subjects # Assuntos/Áreas
    resources :questions # Perguntas
  end
  
  devise_for :admins, skip:  [:registrations]
  devise_for :users
 
  get 'inicio', to: 'site/welcome#index'
  get 'backoffice', to: 'admins_backoffice/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

time_to_answer/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # Kaminari
  paginates_per 5
end

time_to_answer/app/models/admin_statistic.rb
class AdminStatistic < ApplicationRecord
  EVENTS = {
    total_users: "TOTAL_USERS",
    total_questions: "TOTAL_QUESTIONS"
  }

  # Scopes
  scope :total_users, -> {
    find_by_event(EVENTS[:total_users]).value
  }

  scope :total_questions, -> {
    find_by_event(EVENTS[:total_questions]).value
  }

  # Class Methods
  def self.set_event(event)
    admin_statistic = AdminStatistic.find_or_create_by(event: event)
    admin_statistic.value += 1
    admin_statistic.save
  end
end

time_to_answer/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

time_to_answer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

time_to_answer/app/models/cep.rb
require 'net/http'
class CEP
  attr_reader :logradouro, :bairro, :localidade, :uf
  
  END_POINT = "https://viacep.com.br/ws/"
  FORMAT = "json"
  
  def initialize(cep)
    cep_econtrado = encontrar(cep) # hash
    preencher_dados(cep_econtrado)
  end

  def endereco
    "#{@logradouro} / #{@bairro} / #{@localidade} - #{@uf}"
  end

  private

  def preencher_dados(cep_econtrado)
    @logradouro = cep_econtrado["logradouro"]
    @bairro     = cep_econtrado["bairro"]
    @localidade = cep_econtrado["localidade"]
    @uf         = cep_econtrado["uf"]
  end

  def encontrar(cep)
    ActiveSupport::JSON.decode(
      Net::HTTP.get(
        URI("#{END_POINT}#{cep}/#{FORMAT}/")
      )
    )
  end
end

time_to_answer/app/models/question.rb
class Question < ApplicationRecord
  searchkick
  
  belongs_to :subject, counter_cache: true, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  # Callback
  after_create :set_statistic

  # Kaminari
  paginates_per 5

  # Scopes
  scope :_search_subject_, ->(page, subject_id){
    includes(:answers, :subject)
    .where(subject_id: subject_id)
    .page(page)
  }

  scope :_search_, ->(page, term){
    includes(:answers, :subject)
    .where("lower(description) LIKE ?", "%#{term.downcase}%")
    .page(page)
  }

  scope :last_questions, ->(page) {
    includes(:answers, :subject).order('created_at desc').page(page)
  }

  private

  def set_statistic
    AdminStatistic.set_event(AdminStatistic::EVENTS[:total_questions])
  end
end

time_to_answer/app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
end

time_to_answer/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :user_profile
  accepts_nested_attributes_for :user_profile, reject_if: :all_blank
  
  # Callback
  after_create :set_statistic

  # Validations
  validates :first_name, presence: true, length: { minimum: 3 }, on: :update, unless: :reset_password_token_present?
  
  # Virtual Attributes
  def full_name
    [self.first_name, self.last_name].join(' ')
  end

  private

  def set_statistic
    AdminStatistic.set_event(AdminStatistic::EVENTS[:total_users])
  end

  def reset_password_token_present?
    !!$global_params[:user][:reset_password_token]
  end
end

time_to_answer/app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

time_to_answer/app/models/user_statistic.rb
class UserStatistic < ApplicationRecord
  belongs_to :user

  # Virtual Attributes
  def total_questions
    self.right_questions + self.wrong_questions
  end

  # Class Methods
  def self.set_statistic(correct, current_user)
    if !!current_user
      user_statistic = UserStatistic.find_or_create_by(user: current_user)
      correct ? user_statistic.right_questions += 1 : user_statistic.wrong_questions += 1
      user_statistic.save
    end
  end
end

time_to_answer/app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

time_to_answer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource
  before_action :check_pagination
  before_action :set_global_params

  protected

    def layout_by_resource
      devise_controller? ? "#{resource_class.to_s.downcase}_devise" : "application"
    end

    def check_pagination
      unless user_signed_in? or admin_signed_in?
        params.extract!(:page)
      end
    end

    def set_global_params
      $global_params = params
    end
end

time_to_answer/app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

time_to_answer/app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  before_action :build_profile
  layout 'users_backoffice'

  private

  def build_profile
    current_user.build_user_profile if current_user.user_profile.blank?
  end
end

time_to_answer/app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object = nil, method = nil)
    (object && method) ? object.model.human_attribute_name(method) : "Informe os parâmetros corretamente!"
  end
end

time_to_answer/app/helpers/application_helper.rb
module ApplicationHelper
end

time_to_answer/app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

time_to_answer/app/helpers/site/search_helper.rb
module Site::SearchHelper
end

time_to_answer/app/helpers/site_helper.rb
module SiteHelper
  def msg_jumbotron
    case params[:action]
    when 'index'
      "Últimas perguntas cadastradas..."
    when 'questions'
      "Resultados par ao termo \"#{sanitize params[:term]}\"..."
    when 'subject'
      "Mostrando questões para o assunto \"#{sanitize params[:subject]}\"..."
    end
  end
end

time_to_answer/app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
  def avatar_url
     avatar = current_user.user_profile.avatar
     avatar.attached? ? avatar : 'img.jpg'
  end
  

end

time_to_answer/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

time_to_answer/app/views/admins_backoffice/admins/shared/_form.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= action_message %></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">

    <% if @admin.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            
            <ul>
              <% @admin.errors.full_messages.each do |message| %>
                <li> <%= message %> </li>
              <% end %>
            </ul>
        </div>
    <% end %>

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <%= @admin.model_name.human %>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">
                       <%= form_with(model: [ :admins_backoffice, @admin ], local: true) do |form| %>
                        
                            <div class="form-group">
                                <%= form.label :email %>
                                <%= form.text_field :email, 
                                         class:"form-control", 
                                        placeholder: t('placeholder.admin_email')  %>
                            </div>
                            
                            <div class="form-group">
                                <%= form.label :password %>
                                <%= form.password_field :password, 
                                         class:"form-control", 
                                         placeholder: t('placeholder.admin_password')  %>
                            </div>

                            <div class="form-group">
                                <%= form.label :password_confirmation %>
                                <%= form.password_field :password_confirmation, 
                                         class:"form-control", 
                                         placeholder: t('placeholder.admin_password_confirmation')  %>
                            </div>

                            <button type="submit" class="btn btn-default">
                              <%= t('button.save') %>
                            </button>
                        <% end %>
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

time_to_answer/app/views/layouts/admin_devise.html.erb
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


   

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'admin_devise' %>

    <% if flash %>
        <% flash.each do |key, value| %>
          <%= javascript_tag do %>
              $.bootstrapGrowl('<%= value %>', {
              type: 'danger', // (null, 'info', 'danger', 'success')
              align: 'right', // ('left', 'right', or 'center')
              allow_dismiss: true, // If true then will display a cross to close the popup.
              stackup_spacing: 10 // spacing between consecutively stacked growls.
              });
          <% end %>
        <% end %>
    <% end %>
</body>

</html>

time_to_answer/app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>TimeToAnswer</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application' %>
  <%= stylesheet_link_tag    'admins_backoffice' %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Backoffice Administrativo</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">            
                        <li>
                          <%= link_to destroy_admin_session_path, method: :delete do %>
                              <i class="fa fa-sign-out fa-fw"></i> Sair
                          <% end %>
                        </li>   
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        
                        <li>
                            <%= link_to admins_backoffice_welcome_index_path do %>
                              <i class="fa fa-dashboard fa-fw"></i> Dashboard
                            <% end %>
                        </li>
                        
                        <li>
                            <%= link_to admins_backoffice_admins_path do %>
                              <i class="fa fa-users fa-fw"></i> Administradores
                            <% end %>
                        </li>    

                        <li>
                            <%= link_to admins_backoffice_subjects_path do %>
                              <i class="fa fa-file-text-o fa-fw"></i> Assuntos/Áreas
                            <% end %>
                        </li>       

                        <li>
                            <%= link_to admins_backoffice_questions_path do %>
                              <i class="fa fa-th-list fa-fw"></i> Perguntas
                            <% end %>
                        </li>                  
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <%= yield %>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'admins_backoffice' %>

    <% if notice %>
        <%= javascript_tag do %>
            $.bootstrapGrowl('<%= notice %>', {
            type: 'success', // (null, 'info', 'danger', 'success')
            align: 'right', // ('left', 'right', or 'center')
            allow_dismiss: true, // If true then will display a cross to close the popup.
            stackup_spacing: 10 // spacing between consecutively stacked growls.
            });
        <% end %>
    <% end %>

</body>

</html>

time_to_answer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1>LAYOUT APPLICATION!!!!</h1>
    <%= yield %>
  </body>
</html>

time_to_answer/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'site' %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'Time to Answer', root_path, class:"navbar-brand" %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav"></ul>
            <%= form_with(url: site_search_path, local: true, method: :get, class:"navbar-form navbar-left") do |form| %>
              <div class="form-group">
                <%= form.text_field :term, class:"form-control", placeholder:"Digite algo..."%>
              </div>
              <button type="submit" class="btn btn-default">Pesquisar</button>
            <% end %>
            <ul class="nav navbar-nav navbar-right">
              <% unless user_signed_in? %>
                <li><%= link_to 'Entrar', new_user_session_path %></li>
                <li><%= link_to 'Cadastrar-se', new_user_registration_path %></li>
              <% else%>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to users_backoffice_welcome_index_path do %>
                          <i class="fa fa-user fa-fw"></i> Perfil
                      <% end %>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                          <i class="fa fa-sign-out fa-fw"></i> Sair
                      <% end %>
                    </li>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
      
      <%= yield %>
    </div> <!-- /container -->


    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'site' %>

    <% if notice %>
        <%= javascript_tag do %>
            $.bootstrapGrowl('<%= notice %>', {
            type: 'success', // (null, 'info', 'danger', 'success')
            align: 'right', // ('left', 'right', or 'center')
            allow_dismiss: true, // If true then will display a cross to close the popup.
            stackup_spacing: 10 // spacing between consecutively stacked growls.
            });
        <% end %>
    <% end %>
  </body>
</html>

time_to_answer/app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'users_backoffice' %>

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col menu_fixed">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <%= link_to image_tag(avatar_url, alt:"...", class:"img-circle profile_img", id:"imgAvatarMd"), '#', "data-toggle":"modal", "data-target":"#avatarModal" %>
              </div>
              <div class="profile_info">
                <span>Seja bem-vindo,</span>
                <h2><%= current_user.full_name %></h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">                  
                  <li>
                    <%= link_to users_backoffice_welcome_index_path do %>
                      <i class="fa fa-home"></i>Início
                    <% end %>
                  </li>
                  <li>
                    <%= link_to users_backoffice_profile_path do %>
                      <i class="fa fa-user"></i>Dados do Perfil
                    <% end %>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <%= image_tag avatar_url, alt:'', id:"imgAvatarSm" %>
                    <%= current_user.email %>
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                        <i class="fa fa-sign-out pull-right"></i>
                        Sair
                      <% end %>
                    </li>
                  </ul>
                </li>

                <li role="presentation" class="dropdown">
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                        <span class="image">
                          <%= image_tag 'img.jpg', alt:"Profile Image" %>
                        </span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image">
                          <%= image_tag 'img.jpg', alt:"Profile Image" %>
                        </span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image">
                          <%= image_tag 'img.jpg', alt:"Profile Image" %>
                        </span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image">
                          <%= image_tag 'img.jpg', alt:"Profile Image" %>
                        </span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="text-center">
                        <a>
                          <strong>See All Alerts</strong>
                          <i class="fa fa-angle-right"></i>
                        </a>
                      </div>
                    </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <%= yield %>
            </div>
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="avatarModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
        <%= form_with(url: users_backoffice_profile_path, model: current_user, class:"form-horizontal form-label-left") do |form| %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Avatar</h4>
          </div>
          <div class="modal-body">
            <%= form.fields_for :user_profile do |profile_form|  %>
              <div class="form-group">
                <%= profile_form.label :avatar %>
                <%= image_tag(avatar_url, alt:"...", class:"img-circle profile_img", id:"imgAvatarLg") %>
                <%= profile_form.file_field :avatar %>
              </div>
            <% end %>
          </div>
          <div class="modal-footer">
            <%= form.submit "Salvar", class:"btn btn-primary" %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
    <!-- /Modal -->


    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'users_backoffice' %>

    <% if notice %>
        <%= javascript_tag do %>
            $.bootstrapGrowl('<%= notice %>', {
            type: 'success', // (null, 'info', 'danger', 'success')
            align: 'right', // ('left', 'right', or 'center')
            allow_dismiss: true, // If true then will display a cross to close the popup.
            stackup_spacing: 10 // spacing between consecutively stacked growls.
            });
        <% end %>
    <% end %>

    <%= javascript_tag do %>
       $(function() {
         $('.datepicker').datepicker();
       });
    <% end  %>
  </body>
</html>